#SPDX-License-Identifier: MIT-0
---
# handlers file for docker-setup

- name: Ubuntu Restart Docker Service
  systemd:
    name: docker
    state: restarted
    enabled: yes

- name: Amazon Restart Docker Service
  systemd:
    name: docker
    state: restarted
    enabled: yes